### ISSUE TITLE
Problema no campo de nome [ Page: sign_up_page ]

### ISSUE THREAD

**Issue by joaoeudes7** [kleberandrade/my-blood-flutter#1]
Descrição:
Na `page` de `sign_up_page` dá erro no input de nome quando colocado algum nome com acentos

Vi que a validação existente apenas checa se está a String vazia (onde o campo de input não está) e ao clicar em registrar trás a mensagem de erro pedindo para inserir o nome, e logo quando removo o caractere com o acento passa a validar como deveria.

E mesmo quando retirado o Caractere e aperto em `Registrar` mostrar um `toast` de "Email Inválido"

**Comment by kleberandrade** [comment]
Acabamos de corrigir este erro, muito obrigado. Eu tinha colocado um REGEX e tinha esquecido de considerar os acentos, então removi essa análise e atualmente só verificamos se não esta vazio o campo de nome.
